# Generated by Django 6.1.1 on 2026-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('educateur(trice)', 'Éducateur(trice)'), ('parent', 'Parent')], help_text="Détermine l'espace personnel et les droits d'accès de l'utilisateur.", max_length=30, verbose_name='Rôle'),
        ),
    ]
