# Generated by Django 6.1.1 on 2026-09-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfants.enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_allergie', models.CharField(max_length=100)),
                ('reaction', models.TextField()),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfants.enfant')),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enfants.groupe'),
        ),
        migrations.CreateModel(
            name='PersonneAutorisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfants.enfant')),
            ],
        ),
    ]
