# Generated by Django 6.1.1 on 2026-09-26 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacturgence',
            name='prenom',
            field=models.CharField(default='À compléter', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Le prénom doit contenir au moins 2 caractères.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant',
            name='prenom',
            field=models.CharField(default='À compléter', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Le prénom doit contenir au moins 2 caractères.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personneautorisee',
            name='prenom',
            field=models.CharField(default='À compléter', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Le prénom doit contenir au moins 2 caractères.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergie',
            name='reaction',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'La réaction doit contenir au moins 2 caractères.')]),
        ),
        migrations.AlterField(
            model_name='allergie',
            name='type_allergie',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, "Le type d'allergie doit contenir au moins 2 caractères.")]),
        ),
        migrations.AlterField(
            model_name='contacturgence',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Le nom doit contenir au moins 3 caractères.')]),
        ),
        migrations.AlterField(
            model_name='contacturgence',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres.', regex='^[0-9]{3}[-. ]?[0-9]{3}[-. ]?[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, "Le nom de l'enfant doit contenir au moins 3 caractères.")]),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Le nom du groupe doit contenir au moins 3 caractères.')]),
        ),
        migrations.AlterField(
            model_name='personneautorisee',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Le nom doit contenir au moins 3 caractères.')]),
        ),
        migrations.AlterField(
            model_name='personneautorisee',
            name='relation',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'La relation doit contenir au moins 2 caractères.')]),
        ),
        migrations.AlterField(
            model_name='personneautorisee',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres.', regex='^[0-9]{3}[-. ]?[0-9]{3}[-. ]?[0-9]{4}$')]),
        ),
    ]
