# Generated by Django 6.1.1 on 2026-09-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_alter_user_telephone'),
        ('enfants', '0002_contacturgence_prenom_enfant_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='enfants', to='compte.parent'),
        ),
    ]
