# Generated by Django 6.1.1 on 2026-09-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_alter_user_telephone'),
        ('enfants', '0003_enfant_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='educateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='compte.educateur'),
        ),
    ]
